spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}fdd88d9df0275c1b37ceb89fc679efa5086803763f4c13b2588915f8f1f7b808'

token:
  expiration_time: 864000000 
  secret: '{cipher}b8d7ad433241cb44c87891bbe82c9bd8aff09c786a09cbfa6c9ae5d9e059575b'

gateway:
  ip: 127.0.0.2
  
order_service:
  url:  http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
