spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 864000
  secret: YOUR_SECRETKEY_20240630_FOR_SPRING_CLOUD_LOGIN
gateway:
  ip: 127.0.0.1
