spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 864000000
  secret: new_user_token_20220525

gateway:
  ip: 127.0.0.1
