spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AYAzc9lxjb8DqF/RggK7XJxyTv2tkYG3U2S/5QrzVDacdD3GOC3KcYhGmU1A+Iwodu+0BVhU6kXCsCZ1uzCROoBaAU+7BtcSzpah8dGGc7VwpFBbWU/YDnN2dKyMEX9QGWD4d229bIGEN/d4Yz0cITa7GtMZpuDvVpqevwF3JAPU0lDqcJ0caJnuDtazbuYbESPGX0HZJiDEW95adjWsFc1sW1WH+XjPqdQ4aBD6rUQtB04uy5EuS94WIKut1xuWX8TK3TQ6LRSJhLL+EjDKkR1n/wfhYf0PyZuwUkksi0TFhH3FIUcJ1q0/XllIk0D2Ib6lIWW5hhtAzvP/gC7g/IPaoqQzEPHmn0mzvNxiVmXZndm68SrZrAysjYbxYZ7yNYobG9XOeeLNKyyVp7+MY9OMLcyd+S61rO6TGI9Bda3hE4OH+S6YLa4TLaa2p//vQ1Hr4cIsPMJha3vCTK+0ioYZL9c5isBMFUdQhPPDY+d/J3O032d6krLATh0GYmpuUQGaX+9DZ73CT1bPW1xqDaX4zz+nRZbFQaBRWokbXVTt23y3V9jNz6nFBXQaww2zuEDz5R3IsibtCvKcuZYuVqCt'
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
