spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 864000
  secret: '{cipher}AQBsKna/2SZSn3zJLNri/7SDdDBCS7dX5j6sJ+WyQtYVhnd3iI3uJtKbOV6iVKCZm9/SqBHjsr7eF3zEaM1lEUjMkV9VdClZoNUW3w7wfdUg3fsf+i06e42+kzydtn6AsDqS8GEy+t1aBlpbVwrbuoTCMhADgUPyXh1+1KLcAb2K2YzjD5rJN7y+ILX8ZNTyApKT9p0ysz74n4VD61BM9N96EEc5bSP9zYnkyGI4Jkl0SQ8dPZFWlhUvHZxaWPvqJoGgijOoRATlZSRQ6DWVgn2i24xORkWFXQJ932/11zZDDDX6ZNMxCFWJXIRG4WKyJknZSqQHxCuIlEalQuTDSd4qlpBtYw5PR3vP12srexAVGj/nkhcBbxvCvsj/OLn/+IS7B/iBcRKjHBK2Lhvv4ZJk/9+6WUvDxlvT+f3T8sie4w=='
gateway:
  ip: 127.0.0.1
