spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 464000000
  secret: 20221215_LGCNS_#4
gateway:
  ip: 127.0.0.1
