spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AQAA+9drgHpsJlFdKdY9tTzVY1BQdgJN8kECY8/Sxe7VNyjambVLxFw8YAPk8JqTusDRZDdvH4v9/eOwdHmh+hyuW3bpaLsMn7azVaSV1afdk2JNSdDjrBPmUqjsZE+TWPROOcC8MbcsUqXyaSK4uoVmEKZwXN1F0Km9k3Rbj9XsiOh19atvw5h5JNzEvNVsdG3J2hHhFVsNnHTBR/oXHGpGZS4F/7whcxuVHGvceysuopQ+1Y04cNNjT4HGg/7M0ncifT5CCzQkDmpIFgwsrW0PZQwLM2P7PSMqqHSxh85uhs2YHxnmjUNxVMKYDzluMYSaJdGf60qu6qPsmzarvXe4OQV/NJXkZDAFdfmwNc25tTYYl+j2olDp8DpyOvzMdpCbm1Z/wbfmtpFYULn4lFV7VyEX51l+NDRHvuFYi1qpRQ==
'
gateway:
  ip: 127.0.0.1
