spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}fdd88d9df0275c1b37ceb89fc679efa5086803763f4c13b2588915f8f1f7b808'

token:
  expiration_time: 864000000 
  secret: '{cipher}e43c521b45ff518dfce5a0bb82c4fa43abc66054482c85f0e55a4c29e8ed431f'

gateway:
  ip: 10.204.136.204
  
order_service:
  url:  http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
